export enum Role {

    CONFIGURATION_READ = "CONFIGURATION_READ",
    CONFIGURATION_UPDATE = "CONFIGURATION_DELETE",

    CREDENTIAL_CREATE = "CREDENTIAL_CREATE",
    CREDENTIAL_READ = "CREDENTIAL_READ",
    CREDENTIAL_DELETE = "CREDENTIAL_DELETE",

    LICENSE_GROUP_CREATE = "LICENSE_GROUP_CREATE",
    LICENSE_GROUP_READ = "LICENSE_GROUP_READ",
    LICENSE_GROUP_UPDATE = "LICENSE_GROUP_UPDATE",
    LICENSE_GROUP_DELETE = "LICENSE_GROUP_DELETE",

    LICENSE_NAME_MAP_CREATE = "LICENSE_NAME_MAP_CREATE",
    LICENSE_NAME_MAP_READ = "LICENSE_NAME_MAP_READ",
    LICENSE_NAME_MAP_UPDATE = "LICENSE_NAME_MAP_UPDATE",
    LICENSE_NAME_MAP_DELETE = "LICENSE_NAME_MAP_DELETE",

    LICENSE_PURL_MAP_CREATE = "LICENSE_PURL_MAP_CREATE",
    LICENSE_PURL_MAP_READ = "LICENSE_PURL_MAP_READ",
    LICENSE_PURL_MAP_UPDATE = "LICENSE_PURL_MAP_UPDATE",
    LICENSE_PURL_MAP_DELETE = "LICENSE_PURL_MAP_DELETE",

    POLICY_CREATE = "POLICY_CREATE",
    POLICY_READ = "POLICY_READ",
    POLICY_UPDATE = "POLICY_UPDATE",
    POLICY_DELETE = "POLICY_DELETE",

    PROXY_CREATE = "PROXY_CREATE",
    PROXY_READ = "PROXY_READ",
    PROXY_UPDATE = "PROXY_UPDATE",
    PROXY_DELETE = "PROXY_DELETE",

    PROXY_AUDIT_READ = "PROXY_AUDIT_READ",

    USERACCOUNT_CREATE = "USERACCOUNT_CREATE",
    USERACCOUNT_READ = "USERACCOUNT_READ",
    USERACCOUNT_UPDATE = "USERACCOUNT_UPDATE",
    USERACCOUNT_DELETE = "USERACCOUNT_DELETE",

    USERACCOUNT_GROUP_CREATE = "USERACCOUNT_GROUP_CREATE",
    USERACCOUNT_GROUP_READ = "USERACCOUNT_GROUP_READ",
    USERACCOUNT_GROUP_UPDATE = "USERACCOUNT_GROUP_UPDATE",
    USERACCOUNT_GROUP_DELETE = "USERACCOUNT_GROUP_DELETE",

}
