name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@6871f53176ad61624f978536bbf089c574dc19a2 # v8

      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: 22
          cache: 'npm'

      - name: npm install
        run: |
          npm install

      - name: npm test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run test

      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Get and tag release version
        run: |
          VERSION=$(npm version patch)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: npm build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build
      
      - name: Upload released files
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          files: |
            dist-zip/*.zip

      - name: Set and tag next RC version
        run: |
          npm version prerelease --preid rc              

      - name: Push changes
        run: |
          git push

      - name: Trigger workflow elomagic/repository:release
        run: | 
          curl --location \
            --request POST \
            --url "https://api.github.com/repos/elomagic/repository/dispatches" \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer ${{ secrets.PAT }}" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --data "{\"event_type\": \"trigger-workflow\", \"client_payload\": {\"skip_owasp_check\": true, \"unit\": false, \"integration\": true}}"
